export type AICodingCategory = "code-completion" | "ai-ide" | "code-review" | "testing-debugging" | "documentation";

export interface AICodingTool {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: AICodingCategory;
  tags: string[];
  url: string;
  affiliateUrl?: string;
  pricing: "free" | "freemium" | "paid";
  featured: boolean;
  logo: string;
  domain?: string;
  pros?: string[];
  cons?: string[];
  useCases?: string[];
}

export const AI_CODING_CATEGORIES: Record<AICodingCategory, { label: string; emoji: string; description: string; gradient: string }> = {
  "code-completion": { label: "Code Completion", emoji: "⚡", description: "Inline AI suggestions that autocomplete code as you type in your editor.", gradient: "from-green-600/30 to-emerald-800/40" },
  "ai-ide": { label: "AI-Native IDEs", emoji: "💻", description: "Full development environments built from the ground up with AI at the core.", gradient: "from-blue-600/30 to-indigo-800/40" },
  "code-review": { label: "Code Review & Analysis", emoji: "🔍", description: "AI tools that review pull requests, find bugs, and suggest improvements.", gradient: "from-purple-600/30 to-violet-800/40" },
  "testing-debugging": { label: "Testing & Debugging", emoji: "🧪", description: "AI-powered tools for generating tests, finding bugs, and debugging code.", gradient: "from-orange-600/30 to-red-800/40" },
  "documentation": { label: "Documentation & Explanation", emoji: "📝", description: "Tools that generate documentation, explain code, and create technical content.", gradient: "from-teal-600/30 to-cyan-800/40" },
};

export const AI_CODING_EDITORIAL = {
  title: "How to Choose the Right AI Coding Assistant in 2026",
  intro: `AI coding assistants have become essential tools for software developers, with studies showing 30-55% productivity gains for common programming tasks. These tools range from inline code completion that predicts your next line of code to full AI-native IDEs that can write, refactor, and debug entire features from natural language descriptions.\n\nThe market has matured rapidly: GitHub Copilot pioneered the category and remains the most widely used, but strong alternatives like Cursor, Codeium, and Amazon Q Developer now compete on features, model quality, and pricing. Key differentiators include which LLMs power the tool, how well it understands your specific codebase, and whether it operates as an editor plugin or a standalone IDE.\n\nPrivacy and IP concerns matter for professional use. Some tools send your code to cloud APIs for processing, while others offer local or on-premise options. Enterprise teams should evaluate data handling policies, SOC 2 compliance, and whether the tool can be restricted to approved code repositories. The productivity gains are real, but only if the tool fits your security requirements and development workflow.`,
  buyerGuide: [
    "Codebase awareness — the best assistants index your entire repository and understand project structure, coding conventions, and dependencies rather than treating each file in isolation.",
    "IDE and language support — verify the tool works with your preferred editor (VS Code, JetBrains, Neovim) and excels at your primary programming languages, as quality varies significantly across languages.",
    "Privacy and data policies — understand where your code is sent, whether it's used to train models, and what on-premise or zero-retention options exist for proprietary codebases.",
    "Beyond autocomplete — evaluate chat interfaces, multi-file editing, test generation, code review, and debugging capabilities, as modern tools do far more than just predict the next line.",
    "Cost per developer — pricing ranges from free tiers to $40+/month per seat; calculate ROI based on actual time savings for your team's workflow rather than headline features.",
  ],
  faq: [
    {
      question: "Will AI coding assistants replace software developers?",
      answer: "No. AI assistants excel at boilerplate code, repetitive patterns, and accelerating known tasks, but they lack the judgment needed for architecture decisions, requirements analysis, and novel problem-solving. They make developers more productive rather than replacing them — similar to how IDEs and Stack Overflow changed development without eliminating developer roles.",
    },
    {
      question: "Is code generated by AI assistants safe to use in production?",
      answer: "AI-generated code should be reviewed like any other code. It can contain bugs, security vulnerabilities, or use deprecated APIs. Most teams treat AI suggestions as a first draft that still needs human review, testing, and validation before merging to production.",
    },
    {
      question: "Which AI coding assistant is best for beginners?",
      answer: "GitHub Copilot is the most beginner-friendly due to its seamless VS Code integration and large community. Cursor is excellent for developers who want a purpose-built AI IDE experience. Both provide chat interfaces where you can ask questions about code in natural language.",
    },
  ],
};

export const AI_CODING_TOOLS: AICodingTool[] = [
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "The original AI pair programmer, now with chat, agents, and multi-file editing",
    description: "GitHub Copilot is the most widely adopted AI coding assistant, used by millions of developers. It started as inline code completion and has evolved into a full AI development platform with chat, workspace agents, multi-file editing, and CLI integration. Copilot integrates natively with VS Code, JetBrains, Neovim, and Visual Studio. Its deep GitHub integration means it understands your repos, PRs, and issues. Copilot X features include pull request summaries, documentation generation, and voice coding.",
    category: "code-completion",
    tags: ["github copilot", "code completion", "ai pair programmer", "vs code", "jetbrains", "github"],
    url: "https://github.com/features/copilot",
    pricing: "freemium",
    featured: true,
    logo: "🐙",
    domain: "github.com",
    pros: ["Largest user base — battle-tested by millions of developers daily", "Deep GitHub integration for PRs, issues, and repository context", "Works in VS Code, JetBrains, Neovim, Visual Studio, and CLI", "Free tier for individual developers and students", "Agent mode for multi-file autonomous coding tasks"],
    cons: ["Code suggestions can sometimes be subtly wrong or insecure", "Enterprise features require the most expensive tier", "Context window limitations can miss important project context", "Privacy concerns about code being sent to cloud for processing"],
    useCases: ["Getting inline code suggestions while writing in your preferred IDE", "Using chat to explain unfamiliar codebases or debug errors", "Generating boilerplate code, tests, and documentation from comments"],
  },
  {
    slug: "cursor",
    name: "Cursor",
    tagline: "AI-native code editor built on VS Code with powerful multi-file editing",
    description: "Cursor is a fork of VS Code rebuilt with AI at the core. Its standout feature is Composer — an agent that can edit multiple files simultaneously to implement features, refactor code, and fix bugs across your codebase. Cursor understands your entire project through codebase indexing and provides context-aware suggestions. Tab completion predicts multi-line edits, and the chat lets you ask questions about your code with full project context. It has quickly become the preferred editor for AI-first developers.",
    category: "ai-ide",
    tags: ["cursor", "ai ide", "code editor", "vs code fork", "multi-file editing", "composer"],
    url: "https://cursor.com",
    pricing: "freemium",
    featured: true,
    logo: "🖱️",
    domain: "cursor.com",
    pros: ["Composer agent can edit multiple files simultaneously for complex changes", "Full codebase indexing provides deeply context-aware suggestions", "VS Code compatibility — all your extensions and keybindings work", "Supports multiple AI models (GPT-4, Claude, etc.)", "Tab completion predicts multi-line edits intelligently"],
    cons: ["Subscription required for heavy usage — free tier is limited", "Being a VS Code fork means it may lag behind VS Code updates", "Can be resource-intensive on older machines", "Some developers prefer staying in their existing editor"],
    useCases: ["Implementing a full feature across multiple files with Composer", "Refactoring a codebase by describing the desired changes in natural language", "Quickly understanding and navigating an unfamiliar codebase via chat"],
  },
  {
    slug: "claude-code",
    name: "Claude Code",
    tagline: "Anthropic's agentic coding tool that lives in your terminal",
    description: "Claude Code is Anthropic's AI coding agent that operates directly in your terminal. Unlike IDE-based tools, it understands your entire codebase, can run commands, edit files, create commits, and execute multi-step development tasks autonomously. It excels at large-scale refactoring, debugging complex issues, and implementing features end-to-end. Claude Code uses Claude's 200K context window to reason about large codebases and maintains a development loop of thinking, editing, testing, and iterating.",
    category: "ai-ide",
    tags: ["claude code", "anthropic", "terminal", "agentic coding", "cli", "autonomous"],
    url: "https://docs.anthropic.com/en/docs/claude-code",
    pricing: "paid",
    featured: true,
    logo: "🟤",
    domain: "anthropic.com",
    pros: ["Terminal-native — works with any editor, any project, any language", "Full codebase understanding with 200K context window", "Can run tests, fix errors, and iterate autonomously", "Excellent at large-scale refactoring and multi-file changes", "Tight git integration for commits, PRs, and branch management"],
    cons: ["Requires Anthropic API access or Claude Pro/Max subscription", "Terminal-based interface has a learning curve for visual thinkers", "Token costs can add up for large codebases and complex tasks", "Newer than Copilot — smaller community and ecosystem"],
    useCases: ["Implementing a full feature from requirements to tested, committed code", "Debugging a complex issue by having the agent investigate and fix it", "Performing large-scale codebase refactoring across hundreds of files"],
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    tagline: "AI code assistant focused on privacy and enterprise security",
    description: "Tabnine is an AI code completion tool that differentiates through privacy and security. It offers on-premise deployment, SOC-2 compliance, and models trained only on permissively licensed code. Tabnine supports 30+ languages and integrates with all major IDEs. For enterprises concerned about code privacy, IP, and compliance, Tabnine is often the top choice over Copilot.",
    category: "code-completion",
    tags: ["tabnine", "code completion", "privacy", "enterprise", "on-premise", "secure ai"],
    url: "https://www.tabnine.com",
    pricing: "freemium",
    featured: true,
    logo: "⚙️",
    domain: "tabnine.com",
    pros: ["On-premise deployment for complete code privacy", "Trained only on permissively licensed code — no IP risk", "SOC-2 compliance and enterprise security certifications", "Supports 30+ programming languages", "Lightweight and fast completions"],
    cons: ["Suggestions are generally less powerful than Copilot or Cursor", "Chat and agent features are less mature than competitors", "Free tier is very limited compared to Copilot free", "Smaller community and less ecosystem integration"],
    useCases: ["Enterprise teams needing AI coding with strict data privacy requirements", "Regulated industries that cannot send code to third-party clouds", "Organizations requiring only permissively-licensed training data"],
  },
  {
    slug: "codeium-windsurf",
    name: "Windsurf (Codeium)",
    tagline: "Free AI coding assistant with IDE and powerful Cascade agent",
    description: "Windsurf, created by the Codeium team, is an AI-native IDE with a powerful Cascade agent for multi-file editing. Codeium's free tier offers unlimited code completions across all major IDEs — a key differentiator. Windsurf's Cascade feature provides agentic coding capabilities similar to Cursor's Composer, enabling complex multi-file changes through natural language instructions.",
    category: "ai-ide",
    tags: ["windsurf", "codeium", "free ai coding", "cascade", "code completion", "ai ide"],
    url: "https://codeium.com",
    pricing: "freemium",
    featured: true,
    logo: "🌊",
    domain: "codeium.com",
    pros: ["Generous free tier with unlimited code completions", "Cascade agent for multi-file autonomous editing", "Fast completions with low latency", "Supports all major IDEs and 70+ languages", "Growing rapidly with strong user satisfaction"],
    cons: ["Smaller user base and community than GitHub Copilot", "Enterprise features and self-hosting still maturing", "IDE may lag behind VS Code in extension compatibility", "Less integrated with existing developer workflows (GitHub, etc.)"],
    useCases: ["Developers wanting free unlimited AI code completions", "Teams evaluating AI coding tools before committing to paid plans", "Building features with multi-file editing via the Cascade agent"],
  },
  { slug: "amazon-codewhisperer", name: "Amazon Q Developer", tagline: "AWS's AI coding assistant with deep cloud and security expertise", description: "Amazon Q Developer (formerly CodeWhisperer) provides AI code suggestions optimized for AWS services and cloud development. It includes security scanning, reference tracking for open-source code, and deep integration with the AWS ecosystem. Free for individual developers with unlimited code suggestions.", category: "code-completion", tags: ["amazon q", "aws", "code completion", "cloud development", "security scanning"], url: "https://aws.amazon.com/q/developer/", pricing: "freemium", featured: false, logo: "🔸", domain: "aws.amazon.com", pros: ["Free tier with unlimited code suggestions for individuals", "Best-in-class AWS service integration and cloud code patterns", "Built-in security scanning identifies vulnerabilities in generated code", "Reference tracking flags code similar to open-source training data", "Works in VS Code, JetBrains, and AWS Cloud9"], cons: ["Code suggestions less strong than Copilot for non-AWS languages", "Heavily optimized for AWS — less useful outside the AWS ecosystem", "Chat and agent features are less mature than competitors", "Smaller community and fewer third-party resources available"], useCases: ["AWS developer wanting AI suggestions optimized for Lambda, S3, and DynamoDB", "Team needing free unlimited code completions with security scanning", "Cloud engineer writing infrastructure-as-code for AWS services"] },
  { slug: "codium-ai", name: "CodiumAI (Qodo)", tagline: "AI-powered test generation and code quality analysis", description: "Qodo (formerly CodiumAI) focuses on code integrity — generating meaningful tests, analyzing code behavior, and suggesting improvements. It generates comprehensive test suites by understanding code logic, edge cases, and expected behaviors. Integrates with VS Code and JetBrains.", category: "testing-debugging", tags: ["qodo", "codium ai", "test generation", "code quality", "edge cases", "vs code"], url: "https://www.qodo.ai", pricing: "freemium", featured: false, logo: "🧪", domain: "qodo.ai", pros: ["Generates meaningful tests that cover edge cases and boundary conditions", "Analyzes function behavior to suggest relevant test scenarios", "Integrates directly into VS Code and JetBrains workflows", "Free tier available for individual developers", "Helps improve test coverage without tedious manual test writing"], cons: ["Generated tests sometimes require manual refinement for complex logic", "Best results with well-structured, smaller functions — struggles with large classes", "Limited language support compared to general-purpose coding assistants", "Test framework support varies by language"], useCases: ["Developer adding comprehensive unit tests to an untested legacy codebase", "Team using AI to generate edge-case tests for payment processing functions", "QA engineer supplementing manual testing with AI-generated test suites"] },
  { slug: "sourcegraph-cody", name: "Sourcegraph Cody", tagline: "AI coding assistant with unmatched codebase context and code search", description: "Cody by Sourcegraph combines AI coding assistance with Sourcegraph's powerful code intelligence. It understands your entire codebase through code graph analysis, providing deeply contextual answers and suggestions. Code search across repositories and context fetching makes it uniquely suited for large, complex codebases.", category: "code-review", tags: ["sourcegraph", "cody", "code search", "context", "enterprise", "code intelligence"], url: "https://sourcegraph.com/cody", pricing: "freemium", featured: false, logo: "🔎", domain: "sourcegraph.com", pros: ["Unmatched codebase context through Sourcegraph's code graph analysis", "Search across all repositories to find relevant code patterns and examples", "Understands cross-repository dependencies and code relationships", "Supports multiple LLM backends for flexibility", "Enterprise-grade with self-hosted deployment options"], cons: ["Full power requires Sourcegraph instance setup and code indexing", "More complex setup than plug-and-play alternatives like Copilot", "Pricing can be steep for Sourcegraph Enterprise with Cody", "Smaller user community than GitHub Copilot or Cursor"], useCases: ["Engineering team navigating a monorepo with millions of lines of code", "Developer asking questions about unfamiliar code across dozens of repositories", "Enterprise with strict data requirements needing self-hosted AI coding assistance"] },
  { slug: "replit-ai", name: "Replit AI", tagline: "Cloud IDE with built-in AI for coding, debugging, and deployment", description: "Replit's AI features are deeply integrated into its cloud development environment. The AI agent can build full applications from natural language descriptions, debug issues, and deploy apps — all in the browser. Replit is particularly strong for rapid prototyping and learning to code.", category: "ai-ide", tags: ["replit", "cloud ide", "ai agent", "prototyping", "deployment", "browser"], url: "https://replit.com", pricing: "freemium", featured: false, logo: "🔁", domain: "replit.com", pros: ["Build and deploy full apps from natural language descriptions in the browser", "Zero setup — no local environment configuration needed", "One-click deployment with custom domains included", "Collaborative multiplayer coding in real time", "Great for learning to code with AI guidance"], cons: ["Cloud-based means latency compared to local development", "Limited to Replit's cloud environment — can't use your own tooling", "Resource limits on free tier restrict serious application development", "Less control over infrastructure compared to traditional hosting"], useCases: ["Non-developer prototyping a web app from a natural language description", "Student learning to code with AI-assisted explanations and debugging", "Startup building and deploying an MVP without local development setup"] },
  { slug: "coderabbit", name: "CodeRabbit", tagline: "AI-powered code review bot that reviews every pull request automatically", description: "CodeRabbit provides automated AI code reviews on every pull request. It analyzes code changes for bugs, security issues, performance problems, and style inconsistencies. Integrates with GitHub and GitLab, providing inline comments and summaries just like a human reviewer.", category: "code-review", tags: ["coderabbit", "code review", "pull request", "github", "gitlab", "automated review"], url: "https://coderabbit.ai", pricing: "freemium", featured: false, logo: "🐰", domain: "coderabbit.ai", pros: ["Automatically reviews every PR — no manual trigger needed", "Provides inline comments on specific lines just like a human reviewer", "Catches bugs, security issues, and performance problems", "Generates PR summaries to help reviewers understand changes quickly", "Free tier available for open-source projects"], cons: ["Can produce false positives that add noise to PR reviews", "May not catch domain-specific logic errors", "Less effective on large PRs with complex architectural changes", "Requires team buy-in to avoid alert fatigue from automated comments"], useCases: ["Engineering team adding an automated first-pass review to every pull request", "Open-source maintainer catching common issues before manual review", "Security-conscious team wanting automated vulnerability scanning on code changes"] },
  { slug: "mintlify", name: "Mintlify", tagline: "AI-powered documentation generation and beautiful docs hosting", description: "Mintlify generates and maintains developer documentation using AI. It analyzes your codebase to generate accurate API docs, guides, and references. The platform also hosts beautiful documentation sites with search, versioning, and analytics built in.", category: "documentation", tags: ["mintlify", "documentation", "api docs", "developer docs", "hosting", "ai generation"], url: "https://mintlify.com", pricing: "freemium", featured: false, logo: "📗", domain: "mintlify.com", pros: ["Beautiful, modern documentation sites out of the box", "AI generates and keeps documentation up to date with code changes", "Built-in search, analytics, and versioning for hosted docs", "MDX-based — easy for developers to write and customize", "Free tier covers small projects with basic hosting"], cons: ["Hosting lock-in — docs are tied to Mintlify's platform", "AI-generated docs still require human review for accuracy", "Customization options are limited compared to building docs from scratch", "Pricing scales with page views on higher tiers"], useCases: ["API company launching polished developer documentation from OpenAPI specs", "Startup generating and hosting product docs with minimal engineering effort", "Developer advocate maintaining docs that auto-update when APIs change"] },
  { slug: "aider", name: "Aider", tagline: "Open-source AI pair programming tool that works in your terminal", description: "Aider is an open-source command-line tool for AI pair programming. It can edit multiple files, understands git history, and works with GPT-4, Claude, and open-source models. Aider maps your entire repository to provide context-aware edits and automatically creates git commits for each change.", category: "ai-ide", tags: ["aider", "open source", "terminal", "pair programming", "git", "multi-model"], url: "https://aider.chat", pricing: "free", featured: false, logo: "🛠️", domain: "aider.chat", pros: ["Free and open-source with active development community", "Works with any LLM — GPT-4, Claude, or local open-source models", "Automatic git commits for every change with meaningful messages", "Repository mapping provides full codebase context to the AI", "Terminal-native — works with any editor and development environment"], cons: ["Terminal-only interface has a learning curve for GUI-oriented developers", "Requires your own API keys — no bundled model access", "Less polished UX compared to IDE-integrated alternatives", "Large repositories can exceed context limits even with repo mapping"], useCases: ["Developer wanting open-source AI pair programming with model flexibility", "Team using local open-source models for air-gapped development", "Programmer making multi-file changes through natural language in the terminal"] },
  { slug: "continue-dev", name: "Continue", tagline: "Open-source AI coding assistant that you can customize and self-host", description: "Continue is an open-source AI coding assistant for VS Code and JetBrains. It supports any LLM (local or cloud), custom slash commands, and context providers. Teams can self-host and customize it to fit their specific workflows, making it the most flexible AI coding tool available.", category: "code-completion", tags: ["continue", "open source", "customizable", "self-hosted", "vs code", "jetbrains"], url: "https://continue.dev", pricing: "free", featured: false, logo: "🔄", domain: "continue.dev", pros: ["Fully open-source and free with no usage limits", "Supports any LLM — local models, OpenAI, Anthropic, or self-hosted", "Custom slash commands and context providers for team-specific workflows", "Works in both VS Code and JetBrains IDEs", "Self-hostable for organizations with strict data privacy requirements"], cons: ["Requires configuration — not plug-and-play like GitHub Copilot", "Code completion quality depends entirely on the chosen LLM", "Smaller community than commercial alternatives", "Some features require technical knowledge to set up and maintain"], useCases: ["Team running local LLMs for code completion in an air-gapped environment", "Developer building custom slash commands for project-specific code generation", "Organization wanting full control over their AI coding assistant and data flow"] },
  { slug: "pieces", name: "Pieces for Developers", tagline: "AI-powered developer productivity suite with on-device processing", description: "Pieces is a developer productivity tool that saves, enriches, and reuses code snippets with AI. It provides on-device AI processing for privacy, context-aware code suggestions, and workflow copilot features. Integrates across browsers, IDEs, and collaboration tools.", category: "documentation", tags: ["pieces", "code snippets", "on-device ai", "productivity", "privacy", "workflow"], url: "https://pieces.app", pricing: "freemium", featured: false, logo: "🧩", domain: "pieces.app", pros: ["On-device AI processing — code never leaves your machine", "Automatically enriches saved snippets with context, tags, and descriptions", "Works across IDEs, browsers, and collaboration tools seamlessly", "Copilot features suggest relevant snippets from your personal library", "Free tier with generous on-device AI capabilities"], cons: ["Requires local compute resources for on-device AI processing", "Snippet library approach is niche compared to full coding assistants", "Smaller user base and community than mainstream tools", "Less useful if you don't frequently reuse code patterns"], useCases: ["Developer building a personal library of reusable code patterns with AI enrichment", "Privacy-conscious engineer wanting AI coding help without cloud data transmission", "Team sharing annotated code snippets across IDE and browser workflows"] },
  { slug: "codeclimate", name: "Code Climate", tagline: "Automated code review and engineering analytics platform", description: "Code Climate provides automated code review with AI-powered analysis for test coverage, maintainability, and code quality. Its Velocity product offers engineering analytics to measure team productivity. Used by thousands of organizations to maintain code quality standards.", category: "code-review", tags: ["code climate", "code quality", "test coverage", "engineering analytics", "maintainability"], url: "https://codeclimate.com", pricing: "freemium", featured: false, logo: "🌡️", domain: "codeclimate.com", pros: ["Automated maintainability and test coverage grading on every commit", "Engineering Velocity product measures team productivity and cycle time", "Identifies code smells, duplication, and complexity automatically", "Free for open-source projects with full quality analysis", "Integrates with GitHub, GitLab, and Bitbucket pull request workflows"], cons: ["Quality analysis focuses on maintainability — not deep bug detection", "Velocity metrics can be controversial as productivity measures", "Language support is limited to major languages only", "Pricing for private repos can be steep for small teams"], useCases: ["Engineering manager tracking test coverage and code quality trends over time", "Team enforcing minimum maintainability standards on every pull request", "CTO using Velocity metrics to identify bottlenecks in the development process"] },
];
